name: butter-labs
favicon: null
layout_spectrum: 0.39732235111296177
typography_spectrum: 0.7265659552067518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03118581953458488
  lightness: 0.26182054867967963
  saturation: 0.44833874562755227
  rhythmicContrast: 0.5293647353537381
purpose: []
